### ISSUE TITLE
Won't open in Xcode 11.4

### ISSUE THREAD

**Issue by brett-eugenelabs** [M2Mobi/Marky-Mark#102]
Project /Users/blah/Development/github/iOS/Marky-Mark/MarkyMark.xcodeproj cannot be opened because it is missing its project.pbxproj file.

Tried cloning and downloading zip

**Comment by jvanzummeren** [comment]
Hi Brett,

Have you tried running `pod install` in the Example folder and open the *.xcworkspace in that folder?

Please let me know if this works :)

Jim

**Comment by brett-eugenelabs** [comment]
🤦‍♂️
Sorry Jim, was a loooong day yesterday.
