### ISSUE TITLE
[iOS ]Unable to add <br/> tag functionality on MarkDowbTextView(). <br/> as it is display on UI.

### ISSUE THREAD

**Issue by zspradipwalghude** [M2mobi/Marky-Mark#107]
Please provide your solution. Is it supported or need to find another way ?

### Marky-Mark information
  * Marky-Mark version: _____
  * MarkDownConfiguration: _____ (View, AttributedString)

#### Used markdown text
What markdown text did you use that caused this issue?
Try to isolate the part causing the issue.

**Comment by jvanzummeren** [comment]
<br/> is HTML, not Markdown. Just use regular new lines if you want to add newlines in Markdown.

Hope this helps.

Kind regards,

Jim

**Comment by pradipwalghude** [comment]
thank you
