### ISSUE TITLE
Couldn't show image when fileName is null

### ISSUE THREAD

**Issue by ALVIN-YANG** [M2Mobi/Marky-Mark#17]
![image](https://cloud.githubusercontent.com/assets/16443929/18925741/b4d4f260-85e7-11e6-9695-38f35f5659fa.png)

**Comment by jvanzummeren** [comment]
Hi ALVIN-YANG,

Could you add some more information to explain the problem you are experiencing?

**Comment by ALVIN-YANG** [comment]
When image  format  is   ![fileName]xxxxxxx  is  ok

but ->   ![]xxxxxxx    is  unable to load  😅

2016-09-29 1:40 GMT+08:00 jvanzummeren <notifications@github.com>:

**Comment by jvanzummeren** [comment]
Thanks for your feedback.

Just pushed a bugfix: 
https://github.com/M2Mobi/Marky-Mark/commit/1a2d4d1a6e8669460ff66c3e2193a56a49de2df0

A new version of the pod containing this fix will be available tomorrow.
