### ISSUE TITLE
Use pods install  clundn't find class 'MarkDownToAttributedStringConverterConfiguration'

### ISSUE THREAD

**Issue by ALVIN-YANG** [M2Mobi/Marky-Mark#18]
![image](https://cloud.githubusercontent.com/assets/16443929/18942000/354b6338-8648-11e6-8254-801a47abb8fc.png)

**Comment by jvanzummeren** [comment]
Should be solved in version 0.1.4.1 (Swift 2.3) and version 0.1.5 (Swift 3), thanks
