### ISSUE TITLE
Right constraint  didn't work

### ISSUE THREAD

**Issue by ALVIN-YANG** [M2Mobi/Marky-Mark#19]
![image](https://cloud.githubusercontent.com/assets/16443929/18951725/3c8b4862-8679-11e6-9ff7-c40202f0e3dd.png)

**Comment by jvanzummeren** [comment]
Just tested. Seems to work for me.
Are you using the `MarkdownToViewConverterConfiguration` or `MarkDownToAttributedStringConverterConfiguration` ?

**Comment by cocotutch** [comment]
I also see the same issue when using `MarkDownToAttributedStringConverterConfiguration` on a `UILabel` and `UITextView`. Left works fine, but right does not.

No issues when using the regular `MarkDownToViewConverterConfiguration`

Left indent also doesn't apply to `ListMarkdownItem` entries in the AttributedString either. :+1:

No biggie, this was solved for me by using an inset on the `UITextView`'s `textContainer` property.

**Comment by jimvanzummeren** [comment]
You are correct. This is actually not consider a bug but is some of the downsides of using only 1 attributed string that offers a lot less layout possibility. If you do know how to do this with a attributed string, please make a pull request :)
