### ISSUE TITLE
Adding Swift 2.0.x compatibility.

### ISSUE THREAD

**Issue by topLayoutGuide** [M2Mobi/Marky-Mark#22]
Hi!

Thanks for solving the last query that I had about Swift 2.2.

I just tried to integrate this into a Swift 2.0 project. It didn't work.

I want to fork the repo and do it myself from the `Tag 1.0.0` release you made. The project files are missing so I cannot build the project myself, sadly 👎 

I'm happy to help maintain this. This library is ridiculously useful! Could you upload the Xcodeproj and associated items? Or is that too much to ask of you? :joy:

Thanks again

**Comment by jimvanzummeren** [comment]
There's nothing else than what is in the Github repository.
To build the project, run a pod install in the Example folder and run the workspace.

You can do the code changes you need from there and post a pull request :)

**Comment by jvanzummeren** [comment]
Dropping support for Swift 2.0
