### ISSUE TITLE
After building getting many errors

### ISSUE THREAD

**Issue by skdevil** [M2Mobi/Marky-Mark#32]
I have downloaded the github repo and ran the pod install on Example folder. 
After building it i am getting many errors. Any idea why ?

<img width="2028" alt="screen shot 2017-09-30 at 7 50 04 pm" src="https://user-images.githubusercontent.com/16999326/31046593-c6c473b8-a618-11e7-9703-c8c68b28b845.png">

**Comment by jvanzummeren** [comment]
What version of xcode are you using?

**Comment by NallapatiMalleswari** [comment]
i am also gettibg toomany errors ,i am using xcode 9.0 swift 4

**Comment by jvanzummeren** [comment]
Can you provide me with a bit more details?
I just downloaded the master branch, ran pod install in the Example folder, opened the markymark.xcworkspace in the Example folder and built the project succesfully using  Xcode 9.0
