### ISSUE TITLE
Unable to create custom Flavor because all bundled rules have 'internal' protection level on the initializer.

### ISSUE THREAD

**Issue by brendan09** [M2Mobi/Marky-Mark#35]
<img width="590" alt="screen shot 2017-10-10 at 5 51 58 pm" src="https://user-images.githubusercontent.com/1717860/31412606-c213f884-ade3-11e7-9754-c9bc5edb96ee.png">

**Comment by jvanzummeren** [comment]
You are right, apparently defining a class as `open` does not generate a public init.

I just opened a pull request to resolve these issues. Will be merged when it's reviewed.
https://github.com/M2Mobi/Marky-Mark/pull/37

In the mean time you can test it by pointing to this commit in your Podfile if needed.
