### ISSUE TITLE
Awesome library! Any chance of SVG support

### ISSUE THREAD

**Issue by loudmouth** [M2Mobi/Marky-Mark#38]
Firstly, I just wanted to say I really think this library is awesome! I love that i don't have to deal with all the asynchronous loading that web views require and that I can throw either `NSAttributedString` or `UIView` into places like `UITableViewCell`—something that web views make less feasible. I also like how you've added functionality for easy extension.

My question is about SVG support for inline images...while I realize I can make my own `LayoutBlockBuilder` to extend functionality, the issue is that if I want to associate my `SVGAttributedStringBlockBuilder` with an `ImageMarkDownItem`, I can't grab the `file` or `altText` from the markdown item as they missing accessibility identifiers and therefore default to `internal`.

Additionally, the niceties you have implemented in your own `TextAttachment` class are also internal and therefore my SVG block builder can't take advantage of that either without copy/pasting the class. 

Can, at minimum, the accessibility identifiers be made `public`? Additionally, I'm curious if you have any thoughts about adding an SVG sub-spec that depends on another framework like [SVGKit](https://github.com/SVGKit/SVGKit) (enables extraction of `UIImage` for injecting for injecting to `NSTextAttachment`), or [SwiftSVG](https://github.com/mchoe/SwiftSVG) (seems to have active maintenance, but no simple UIImage extraction).

**Comment by jvanzummeren** [comment]
Thanks, appreciated. :) 

About the SVG support, we don't have any SVG support since it's not supported natively and as you said, can only be achieved with another framework. Since, as far as i know, it's not possible to have optional dependancies in Cocoapods, i don't want to force everyone who is using Markymark to also have a dependancy on either SVGKit of SwiftSVG. 

That said, i do not mind having the properties you mentions as public properties, in my opinion it would indeed be the best solution to create your own layout for this case. 

Would you mind making a pull request for this?

**Comment by loudmouth** [comment]
I'd be happy to submit a PR making changing the previously mentioned accessibility identifiers.

Regarding optional dependencies, this actually is totally achievable in a Cocoapod spec file using the [subspec API](https://guides.cocoapods.org/syntax/podspec.html#subspec). Including an SVG extension would simply require opting in in a consumer's Podfile:

`pod 'markymark/SVG'`

```ruby
#!/usr/bin/ruby

Pod::Spec.new do |s|
  s.name = 'markymark'

  # Include only the core by defualt.
  s.default_subspec = 'Core'

  s.subspec 'Core' do |cs|
  end

  s.subspec 'SVG' do |svg|
    svg.dependency 'SwiftSVG'
  end
end
```

**Comment by loudmouth** [comment]
It turns out that on a fresh clone, opening the project is not possible. According to Xcode, there is no `project.pbxproj` file. Is there a specific workflow for contributors?


![screen shot 2017-11-23 at 10 29 47](https://user-images.githubusercontent.com/4554909/33166067-3f609f78-d039-11e7-8413-ab8e43508212.png)

**Comment by tpgmeligmeyling** [comment]
@loudmouth 
You should change direction to the Example folder, run pod install, and work from `Example/markymark.xcworkspace`.

**Comment by loudmouth** [comment]
Thanks @jvanzummeren and @tpgmeligmeyling for helping out so quickly!

Quick note on my solution for SVGs: being able to create my own builder for `ImageMarkDownItem`, I was able to use the Contentful Images API to render the SVG server-side and send a jpg and it worked beautifully!
