### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by Romasik720** [M2Mobi/Marky-Mark#69]
<img width="841" alt="screen shot 2018-10-11 at 23 47 18" src="https://user-images.githubusercontent.com/17250126/46832943-0ebcea00-cdb0-11e8-96af-efb6e4cc49fb.png">

**Comment by Romasik720** [comment]
<img width="415" alt="screen shot 2018-10-11 at 23 49 28" src="https://user-images.githubusercontent.com/17250126/46833048-504d9500-cdb0-11e8-943e-d6a5bd0253c7.png">

**Comment by jvanzummeren** [comment]
Has been solved

**Comment by idsky2** [comment]
Just installed markymark 4.0.2 and got this error.  XCode 9.4.1

**Comment by jvanzummeren** [comment]
Hi idsky2,

I noticed you are using Xcode 9, which Apple is not supporting anymore and you will not able to submit your app built with Xcode 9 after March this year. I recommend upgrading to Xcode 10 and the latest version of MarkyMark which should resolve this issue.

Kind regards,

Jim
