### ISSUE TITLE
List View has incorrect height

### ISSUE THREAD

**Issue by christie-alphero** [M2Mobi/Marky-Mark#70]
Hey, I'm using the markdown text view inside a tableview cell.
The list view and list view item views don't have any sort of constraints or pinning, so in a cell are squashed to the nib height rather then having an intrinsic size.

Let me know if you need any further information.

**Comment by jvanzummeren** [comment]
I’m not sure if this is an issue related to MarkyMark, is the same set-up with a multi line UILabel working correctly?

Regards,

Jim
