### ISSUE TITLE
Make markymark safe to use in extensions

### ISSUE THREAD

**Issue by mhoeller-clue** [M2Mobi/Marky-Mark#71]
Currently, when trying to use markymark via cocoapods, and linking it into a framework, we get the compiler error `'shared' is unavailable: Use view controller based solutions where appropriate instead.`. This is because `UIApplication` cannot be used from extensions or dynamically linked frameworks.
A possible solution to make markymark extension safe is outlined here: https://gist.github.com/natecook1000/151d8de423eb77fc87bf#gistcomment-1656503

**Comment by jvanzummeren** [comment]
Thanks for your input.

Is it possible to be any more specific? Which parts of markymark are not safe for extensions and whats solution are you proposing?

Regards,

Jim

**Comment by mhoeller-clue** [comment]
The problem is the use of `UIApplication.shared.openURL(url)` in `AttributedInteractiveLabel`. `UIApplication` is not extension safe.
The proposed solution is to "hide" the API usage by using `NSClassFromString(@"UIApplication")` instead of `UIApplication` directly. This approach apparently also worked for [SDWebImage](https://github.com/SDWebImage/SDWebImage/issues/1082).

**Comment by mhoeller-clue** [comment]
An alternate, less hacky, solution could be delegation, where `AttributedInteractiveLabel` would have a delegate that gets informed about opening the url, but that might be a breaking change in the API. Also the `AttributedInteractiveLabel` will not be a drop-in solution any more if link handling is required.

**Comment by jvanzummeren** [comment]
Thanks for your input @mhoeller-clue, i looked into your pull-request and made https://github.com/M2Mobi/Marky-Mark/pull/74 inspired by your approach. 

This pull request will allow markymark to compile in extension by using NSSelectorFromString("sharedApplication") instead using UIApplication.shared directly.

Also, this pull request will allow customization of the open url behavior by providing an implementation of URLOpener

My collegues will review the pull request and i will let you know as soon as i release a new version. Also, let me know what you think of this approach!

**Comment by mhoeller-clue** [comment]
Looks perfect! It has much deeper integration throughout the system and extends the example project too 👍 
Thanks for putting the work into this library! Looking forward to the new version.

**Comment by jvanzummeren** [comment]
Just release the new version!
