### ISSUE TITLE
Ability to intercept links

### ISSUE THREAD

**Issue by illyabusigin** [M2Mobi/Marky-Mark#73]
Currently, markymark handles opening all links internally in `AttributedInteractiveLabel` with:

```swift
 @objc func didTap(_ tapGesture:UITapGestureRecognizer) {
        guard let view = tapGesture.view else { return }

        let locationInView = tapGesture.location(in: view)
        if let url = getUrlAtLocationInView(locationInView) {
            UIApplication.shared.openURL(url)
        }
    }
```

I would like to be able to intercept link handling and handle them myself. This would let me use `SFSafariViewController` to open the link or perform other actions. What would be the be the best way to bring this capability to markymark? Originally I was thinking of adding a link handler on `AttributedInteractiveLabel` like so:

```swift
let linkHandler: ((_ link: URL) -> Void)? = nil

...

@objc func didTap(_ tapGesture:UITapGestureRecognizer) {
    guard let view = tapGesture.view else { return }

    let locationInView = tapGesture.location(in: view)
    if let url = getUrlAtLocationInView(locationInView) {
        if let handler = linkHandler {
            handler(url)
        } else {
            UIApplication.shared.openURL(url)
        }
    }
}
```

Given how it's used internally I'm not sure that's the right approach.

**Comment by jvanzummeren** [comment]
Hi @illyabusigin,

I just created https://github.com/M2Mobi/Marky-Mark/pull/74, this will allow injecting opening url behavior by providing an implementation of URLOpener to Markymark. I will let you know when this feature is released.

**Comment by jvanzummeren** [comment]
Just release the new version!
