### ISSUE TITLE
Handle tap on elements

### ISSUE THREAD

**Issue by borgeser** [M2Mobi/Marky-Mark#90]
Hi,

I'm currently using Marky-Mark and I love it, it saves me a lot of time.

I need to handle touches on markdown elements (in my case, I need to open a new view controller on click on some images). What would be the simplest way to do that?

I was thinking using a custom LayoutBlockBuilder with a delegate and a rule which overrides the default "image" rule. But I somehow need to pass my delegate to the custom LayoutBlockBuilder. Or maybe it could be a native feature for every items?

Thanks a lot !

**Comment by jvanzummeren** [comment]
Hi,

An easy way i can think of right now is using the converter hook. It gets called every time a markdown item is converted to a view and passes both the related view and markdown item. I think if you type check or cast the view and/or markdown item you can add a gesture recognizer to add the desired interaction.

The option you suggested might also be nice to create your own layout builder for images. It is not needed to create another image rule in this case.

Let me know if this works out, if not, i can assist you this monday.

Regards,

Jim
M2mobi

**Comment by borgeser** [comment]
I used the converter hook and it worked like a charm.

Thanks a lot.

**Comment by jvanzummeren** [comment]
Great!
