### ISSUE TITLE
Ability to customize UITextView that's created in attributedString configuration of MarkdownTextView

### ISSUE THREAD

**Issue by lvnkmn** [M2Mobi/Marky-Mark#92]
Hi there!

It would be really nice if `UITextViews` created by `MarkDownAsAttributedStringViewConfiguration` could be further customized just like views created in `MarkDownAsViewViewConfiguration` can be customized though the `public var onDidConvertMarkDownItemToView:((_ markDownItem: MarkDownItem, _ view: UIView) -> Void)?` closure.

this way scrolling, contentInsets etc. can be changed as desired.

**Comment by lvnkmn** [comment]
I'll create a PR for this in a bit.

**Comment by Basca** [comment]
Released as version 9.2.1: https://github.com/M2Mobi/Marky-Mark/releases/tag/9.2.1

**Comment by lvnkmn** [comment]
Super. Thanks Bas!
