### ISSUE TITLE
[Q] - Using Local Images

### ISSUE THREAD

**Issue by rlaurb** [M2Mobi/Marky-Mark#96]
I am using Marky-Mark with an internal online help system in my app. I am retrieving text in markdown format, using Marky-Mark to render it to an attributed string, then displaying it. But now I want to include an image, which is going to be stored in the application's internal structure (not an external URL).

So I need to statically specify a file that Marky-Mark can find, but that references a location that is in the iOS app bundle. How can I do that? I don't (and can't) know the full path for the image file as it will exist in my customer's device.

Can you help?

**Comment by Basca** [comment]
We already support bundled images.
They work just like an `UIImage(named: <name>)` would work.
In the example project you can find the following line in the example markdown text:

```
Inline image ![Apple logo](appleLogo) Apple logo ![Apple logo](appleLogoSmall)
```

The appleLogo and appleLogoSmall both are coming from the Images.xcassets of the project.
Hope to have provided you with enough information

**Comment by Basca** [comment]
Closed due to inactivity
